// clients/react-app/src/components/login.tsx
import React from "react";

import PropTypes from "prop-types";
import {
  createStyles,
  Theme,
  withStyles,
  WithStyles
} from "@material-ui/core/styles";
import TextField from "@material-ui/core/TextField";
import { Button } from "@material-ui/core";

import { encode } from "base-64";
import { Redirect } from "react-router";

const styles = (theme: Theme) =>
  createStyles({
    textField: {
      display: "block",
      marginLeft: theme.spacing.unit,
      marginRight: theme.spacing.unit
    },
    dense: {
      marginTop: 19
    },
    menu: {
      width: 200
    }
  });

export interface Props extends WithStyles<typeof styles> {}

export interface Form {
  username: string;
  password: string;
}

export interface State extends Form {
  logged: boolean;
}

class TextFields extends React.Component<Props, State> {
  state: State = {
    username: "",
    password: "",
    logged: (localStorage.getItem('credential') !== null),
  };

  handleChange = (name: keyof Form) => (
    event: React.ChangeEvent<HTMLInputElement>
  ) => {
    this.setState({ [name]: event.target.value } as Pick<Form, keyof Form>);
  };

  handleSubmit = async () => {
    const { username, password } = this.state;

    const headers = new Headers();
    headers.set("Authorization", `Basic ${encode(`${username}:${password}`)}`);

    const response = await fetch("http://localhost:3000/threads", {
      method: "GET",
      headers: headers,
      mode: "cors"
    });

    if (response.status !== 401) {
      localStorage.setItem(
        "credential",
        JSON.stringify({
          username,
          password
        })
      );

      this.setState({
        logged: true
      });
    }
  };

  render() {
    if (this.state.logged) {
      return <Redirect to="/" />;
    }

    const { classes } = this.props;

    return (
      <form onSubmit={this.handleSubmit} autoComplete="off">
        <TextField
          id="standard-name"
          label="Name"
          className={classes.textField}
          value={this.state.username}
          onChange={this.handleChange("username")}
          margin="normal"
        />
        <TextField
          id="standard-password-input"
          label="Password"
          className={classes.textField}
          type="password"
          value={this.state.password}
          onChange={this.handleChange("password")}
          margin="normal"
        />
        <Button variant="contained" color="primary" onClick={this.handleSubmit}>
          Sign up
        </Button>
      </form>
    );
  }
}

(TextFields as React.ComponentClass<Props>).propTypes = {
  classes: PropTypes.object.isRequired
} as any;

const Login = withStyles(styles)(TextFields);

export { Login };

// clients/angular/src/app/login/login.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { encode } from 'base-64';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  @Input() credential = {
    username: '',
    password: '',
  };

  constructor(public router: Router) { }

  ngOnInit() {
  }

  async onSubmit() {
    const username = this.credential.username;
    const password = this.credential.password;

    const headers = new Headers();
    headers.set(
      'Authorization',
      `Basic ${encode(`${username}:${password}`)}`
    );

    const response = await fetch('http://localhost:3000/threads', {
      method: 'GET',
      headers,
      mode: 'cors'
    });

    if (response.status !== 401) {
      localStorage.setItem('credential', JSON.stringify({
        username,
        password
      }));

      this.router.navigate(['']);
    }
  }
}
